use gateway_core::gateway::publisher::Channel;
use local::mqtt_connectivity::mqtt_client;
use local::types::config::Config;

use std::fs::File;
use std::sync::Arc;
use async_mutex::Mutex;

#[tokio::main]
async fn main() -> () {
    //Read configuration file config.json where all the MQTT broker and IOTA node coordinates are specified
    let config: Config = serde_json::from_reader(File::open("config.json").unwrap()).unwrap();

    println!("Starting....");
    // The following line creates the Channel / Author to start the stream
    // And is an asynchronous function to avoid messages congestion
    let channel = Arc::new(Mutex::new(Channel::new(
        &config.node,
        config.local_pow,
        None, // TODO We are creating a random seed ATM. Future seed can be generated by DID.
    ).await));
    // Here the channel is announced and the tuple values are sent to console
    let (addr, msg) = match channel.lock().await.open().await {
        Ok(a) => a,
        Err(_) => panic!("Could not connect to IOTA Node, try with another node!"),
    };
    println!("Channel root: {:?}", format!("{}:{}", addr, msg));
    println!(
        "\n To read the messages copy the channel root into https://explorer.iot2tangle.io/ \n "
    );

    mqtt_client::start(
        config.username,
        config.password,
        config.broker_ip,
        config.broker_port,
        config.topic,
        channel,
    )
    .await
}
// TODO At the moment when this code is executed it creates an fixed author
// TODO in the future, this will be changed so that multiple authors can
// TODO can be created.